version: "3.8"

services:
  postgres:
    image: postgres:17
    container_name: swp391-postgres
    environment:
      POSTGRES_DB: swp391
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    container_name: swp391-app
    build: .
    ports:
      - "8081:8081"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/swp391
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 12345
      JWT_SECRET: b26506d8765608dc6d817bf4f004b241417ca0efad4053a70f8e80276fbf5a64

volumes:
  pgdata:
